version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/client

permissions:
  - object: scripts/
    mode: 777
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh  # Optional: Cleanup before installation
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/stop-containers.sh  # Stop running containers
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start-containers.sh  # Start containers after installation
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate-service.sh  # Validate backend service is running
      timeout: 300
      runas: ubuntu

    - location: scripts/validate-nginx.sh  # Validate Nginx service is running
      timeout: 300
      runas: ubuntu

