version: "3.8"
services:
  react_app:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:  
      - NODE_ENV=production  # Set the environment variable for production mode
    networks:  
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]  
      interval: 30s  
      timeout: 3s  
      retries: 3  
      start_period: 5s 

networks:  
  app_network:
    driver: bridge