import {
  StartupBuildingMvp,
  StartupBusiness,
  StartupCustomer,
  StartupDesign,
  StartupFundraising,
  StartupGrowth,
  StartupIdeaValidation,
  StartupLegal,
  StartupMarketResearch,
  StartupNetworking,
  StartupProduct,
  StartupTeamBuilding,
} from "@/assets/svgs";

export const timelineContent = [
  {
    heading: "Idea validation",
    subHeading: "This module focuses on proofing your Problem & Solution fit",
    detail:
      "before getting invested further in the process. We can’t highlight enough about the criticality of this module.",
    status: "Tasks Completed",
    image: StartupIdeaValidation,
    direction: "right",
    totalTask: "2",
    completedTask: "0",
    to: "idea-validation",
    type: "ideaValidation",
  },
  {
    heading: "Market research",
    subHeading:
      "Here you start to test your idea (the Solution part) in the real-",
    detail:
      "world. Starting off with market research to define your value-proposition through building your first landing page hero section",
    image: StartupMarketResearch,
    direction: "left",
    totalTask: "2",
    completedTask: "0",
    to: "market-research",
    type: "marketResearch",
  },
  {
    heading: "Building the MVP",
    subHeading: "Develop a Minimum Viable Product to test core features. ",
    detail:
      "Get user feedback early, minimizing risk while proving your idea’s potential in real-world scenarios.",
    image: StartupBuildingMvp,
    direction: "right",
    totalTask: "2",
    completedTask: "0",
    to: "building-the-mvp",
    type: "",
  },
  {
    heading: "Growth and User Acquisition",
    subHeading: "Learn strategies to attract and retain your first users. ",
    detail:
      "Focus on scalable growth, refining your value proposition, and optimizing your acquisition channels.",
    image: StartupGrowth,
    direction: "left",
    totalTask: "2",
    completedTask: "0",
    to: "growth-the-use-acquisition",
    type: "",
  },
  {
    heading: "Design and Branding",
    subHeading: "Establish a strong brand identity that resonates with your",
    detail:
      "your target audience. This module covers visual design, brand messaging, and consistency across all touchpoints.",
    image: StartupDesign,
    direction: "right",
    totalTask: "2",
    completedTask: "0",
    to: "design-and-branding",
    type: "",
  },
  {
    heading: "Product development",
    subHeading: "Transform your MVP into a fully-fledged product. ",
    detail:
      "This module guides you through iterative development, user feedback integration, and feature prioritization.",
    image: StartupProduct,
    direction: "left",
    totalTask: "2",
    completedTask: "0",
    to: "product-development",
    type: "",
  },
  {
    heading: "Business model and Revenue",
    subHeading: "Define your revenue streams and refine your business model.",
    detail:
      "Learn how to build a sustainable financial foundation that aligns with your startup’s goals.",
    image: StartupBusiness,
    direction: "right",
    totalTask: "2",
    completedTask: "0",
    to: "business-model-and-revenue",
    type: "",
  },
  {
    heading: "Fundraising and Pitching",
    subHeading: "Master the art of pitching to investors. This module covers",
    detail:
      "pitch deck creation, investor relations, and strategies for securing the funding you need.",
    image: StartupFundraising,
    direction: "left",
    totalTask: "2",
    completedTask: "0",
    to: "fundraising-and-pitching",
    type: "",
  },
  {
    heading: "Team building and management",
    subHeading: "Build and manage a team that can execute your vision.",
    detail:
      "Learn about recruitment, leadership, and maintaining a productive and positive startup culture.",
    image: StartupTeamBuilding,
    direction: "right",
    totalTask: "2",
    completedTask: "0",
    to: "team-building-and-management",
    type: "",
  },
  {
    heading: "Legal and operation setup",
    subHeading: "Ensure your startup is legally compliant and operationally",
    detail:
      "operationally sound. This module covers legal structures, contracts, intellectual property, and efficient operations.",
    image: StartupLegal,
    direction: "left",
    totalTask: "2",
    completedTask: "0",
    to: "legal-and-operation-setup",
    type: "",
  },
  {
    heading: "Customer retention and engagement",
    subHeading: "Develop strategies to keep your users engaged and loyal.",
    detail:
      "Focus on user feedback, product iterations, and building long-term customer relationships.",
    image: StartupCustomer,
    direction: "right",
    totalTask: "2",
    completedTask: "0",
    to: "customer-retention-and-engagement",
    type: "",
  },
  {
    heading: "Networking and community building",
    subHeading: "Connect with like-minded founders and mentors.",
    detail:
      "This module emphasizes the importance of building a supportive network and an engaged startup community.",
    image: StartupNetworking,
    direction: "left",
    totalTask: "2",
    completedTask: "0",
    to: "networking-and-community-building",
    type: "",
  },
];
